Repository vue-email/vue-email, pull requests merged in 2023-09, with the labels that each got.

#62 fix: updated html parser from cheerio to htmlparser2
  package.json
  pnpm-lock.yaml
  src/components/ETailwind.ts
Labels: bug, enhancement

#43 [FEATURE] i18n support
  docs/components/content/emails/RenderEmailTemplate.vue
  docs/content/1.getting-started/2.installation.md
  docs/content/1.getting-started/4.i18n.md
  docs/content/2.components/12.markdown.md
  package.json
  playgrounds/nuxt/nuxt.config.ts
  playgrounds/nuxt/package.json
  playgrounds/nuxt/server/api/test.get.ts
  pnpm-lock.yaml
  src/compiler/config.ts
  src/compiler/template.ts
  src/composables/render.ts
  src/nuxt/module.ts
  src/nuxt/runtime/server/services/useCompiler.ts
  src/nuxt/runtime/templates/vue-email.ts
  src/plugin/index.ts
  src/types/compiler.ts
  src/types/config.ts
  src/types/index.ts
  src/utils/assign-deep.ts
  tests/compiler/compiler.spec.ts
  tests/compiler/templates/Translate.vue
Labels: documentation, enhancement

#66 docs: moving to @nuxthq/elements
  client/components/EmptyState.vue
  docs/.env.example
  docs/app.config.ts
  docs/app.vue
  docs/components/Footer.vue
  docs/components/Header.vue
  docs/components/Illustration.vue
  docs/components/OgImage/OgImageDocs.vue
  docs/components/home/HomeDemo.vue
  docs/content/1.getting-started/5.examples.md
  docs/content/changelog.md
  docs/error.vue
  docs/layouts/default.vue
  docs/layouts/docs.vue
  docs/nuxt.config.ts
  docs/package.json
  docs/pages/[...slug].vue
  docs/pages/index.vue
  docs/pages/playground.vue
  docs/plugins/ui.ts
  docs/tailwind.config.ts
  pnpm-lock.yaml
Labels: documentation

#68 docs: Updated Sendgrid integration
  docs/content/5.integrations/sendgrid.md
Labels: documentation

#63 fix: Auto import `.vue` components that live in `emails` folder
  .eslintrc
  .vscode/settings.json
  docs/content/1.getting-started/3.SSR.md
  docs/content/5.integrations/aws-ses.md
  docs/content/5.integrations/mailersend.md
  docs/content/5.integrations/nodemailer.md
  docs/content/5.integrations/plunk.md
  docs/content/5.integrations/postmark.md
  docs/content/5.integrations/resend.md
  docs/content/5.integrations/sendgrid.md
  package.json
  playgrounds/nuxt/composables/useEmail.ts
  playgrounds/nuxt/emails/Hello.vue
  playgrounds/nuxt/emails/test.ts
  playgrounds/nuxt/emails/twitch-reset-password.vue
  playgrounds/nuxt/emails/vercel-invite-user.vue
  playgrounds/nuxt/emails/yelp-recent-login.vue
  playgrounds/nuxt/nuxt.config.ts
  playgrounds/nuxt/server/api/test.get.ts
  pnpm-lock.yaml
  src/compiler/index.ts
  src/compiler/template.ts
  src/composables/render.ts
  src/nuxt/module.ts
  src/nuxt/runtime/server/services/useCompiler.ts
  src/types/compiler.ts
  src/utils/cleanup.ts
  src/utils/import-from-string/index.ts
  src/utils/import-from-string/utils.ts
  tests/Head.spec.ts
  tests/compiler/compiler.spec.ts
  tests/compiler/templates/Hello.vue
  tests/compiler/templates/Translate.vue
  tests/compiler/templates/TsScriptSetup.vue
  tests/compiler/templates/UseOtherComponents.vue
  tests/compiler/templates/test.ts
Labels: enhancement
